workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    stackone-specs:
        inputs:
            - location: https://api.eu1.stackone.com/oas/stackone.json
            - location: https://api.eu1.stackone.com/oas/hris.json
            - location: https://api.eu1.stackone.com/oas/ats.json
            - location: https://api.eu1.stackone.com/oas/lms.json
            - location: https://api.eu1.stackone.com/oas/iam.json
            - location: https://api.eu1.stackone.com/oas/crm.json
            - location: https://api.eu1.stackone.com/oas/marketing.json
            - location: https://api.eu1.stackone.com/oas/ticketing.json
            - location: https://api.eu1.stackone.com/oas/documents.json
            - location: https://api.eu1.stackone.com/oas/screening.json
            - location: https://api.eu1.stackone.com/oas/messaging.json
            - location: https://api.eu1.stackone.com/oas/accounting.json
        registry:
            location: registry.speakeasyapi.dev/stackone/stackone/stackone-specs
targets:
    stack-one:
        target: php
        source: stackone-specs
        publish:
            packagist:
                username: $PACKAGIST_USERNAME
                token: $PACKAGIST_TOKEN
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/stackone/stackone/stackone-specs-php-code-samples
            blocking: false
