<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Models\Components;
use StackOne\client\Utils\SpeakeasyMetadata;
class AtsUpdateInterviewNoteRequest
{
    /**
     * The account identifier
     *
     * @var string $xAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-account-id')]
    public string $xAccountId;

    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var string $subResourceId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=subResourceId')]
    public string $subResourceId;

    /**
     *
     * @var Components\AtsUpdateNotesRequestDto $atsUpdateNotesRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\AtsUpdateNotesRequestDto $atsUpdateNotesRequestDto;

    /**
     * Set to "heartbeat" to enable keep-alive newline heartbeats during long-running requests. Response includes Preference-Applied: heartbeat header when honored. (RFC 7240)
     *
     * @var ?string $prefer
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Prefer')]
    public ?string $prefer = null;

    /**
     * @param  string  $xAccountId
     * @param  string  $id
     * @param  string  $subResourceId
     * @param  Components\AtsUpdateNotesRequestDto  $atsUpdateNotesRequestDto
     * @param  ?string  $prefer
     * @phpstan-pure
     */
    public function __construct(string $xAccountId, string $id, string $subResourceId, Components\AtsUpdateNotesRequestDto $atsUpdateNotesRequestDto, ?string $prefer = null)
    {
        $this->xAccountId = $xAccountId;
        $this->id = $id;
        $this->subResourceId = $subResourceId;
        $this->atsUpdateNotesRequestDto = $atsUpdateNotesRequestDto;
        $this->prefer = $prefer;
    }
}