<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Models\Components;
use StackOne\client\Utils\SpeakeasyMetadata;
class DocumentsUploadFileRequest
{
    /**
     * The account identifier
     *
     * @var string $xAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-account-id')]
    public string $xAccountId;

    /**
     *
     * @var Components\UnifiedUploadRequestDto $unifiedUploadRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\UnifiedUploadRequestDto $unifiedUploadRequestDto;

    /**
     * The session token
     *
     * @var ?string $xStackoneApiSessionToken
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-stackone-api-session-token')]
    public ?string $xStackoneApiSessionToken = null;

    /**
     * Set to "heartbeat" to enable keep-alive newline heartbeats during long-running requests. Response includes Preference-Applied: heartbeat header when honored. (RFC 7240)
     *
     * @var ?string $prefer
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Prefer')]
    public ?string $prefer = null;

    /**
     * @param  string  $xAccountId
     * @param  Components\UnifiedUploadRequestDto  $unifiedUploadRequestDto
     * @param  ?string  $xStackoneApiSessionToken
     * @param  ?string  $prefer
     * @phpstan-pure
     */
    public function __construct(string $xAccountId, Components\UnifiedUploadRequestDto $unifiedUploadRequestDto, ?string $xStackoneApiSessionToken = null, ?string $prefer = null)
    {
        $this->xAccountId = $xAccountId;
        $this->unifiedUploadRequestDto = $unifiedUploadRequestDto;
        $this->xStackoneApiSessionToken = $xStackoneApiSessionToken;
        $this->prefer = $prefer;
    }
}