<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Models\Components;
use StackOne\client\Utils\SpeakeasyMetadata;
class IamUpdateUserRequest
{
    /**
     * The account identifier
     *
     * @var string $xAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-account-id')]
    public string $xAccountId;

    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var Components\IamUpdateUserRequestDto $iamUpdateUserRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\IamUpdateUserRequestDto $iamUpdateUserRequestDto;

    /**
     * Set to "heartbeat" to enable keep-alive newline heartbeats during long-running requests. Response includes Preference-Applied: heartbeat header when honored. (RFC 7240)
     *
     * @var ?string $prefer
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Prefer')]
    public ?string $prefer = null;

    /**
     * @param  string  $xAccountId
     * @param  string  $id
     * @param  Components\IamUpdateUserRequestDto  $iamUpdateUserRequestDto
     * @param  ?string  $prefer
     * @phpstan-pure
     */
    public function __construct(string $xAccountId, string $id, Components\IamUpdateUserRequestDto $iamUpdateUserRequestDto, ?string $prefer = null)
    {
        $this->xAccountId = $xAccountId;
        $this->id = $id;
        $this->iamUpdateUserRequestDto = $iamUpdateUserRequestDto;
        $this->prefer = $prefer;
    }
}