<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Models\Components;
use StackOne\client\Utils\SpeakeasyMetadata;
class MarketingCreateEmailTemplateRequest
{
    /**
     * The account identifier
     *
     * @var string $xAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-account-id')]
    public string $xAccountId;

    /**
     *
     * @var Components\MarketingCreateEmailTemplateRequestDto $marketingCreateEmailTemplateRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\MarketingCreateEmailTemplateRequestDto $marketingCreateEmailTemplateRequestDto;

    /**
     * Set to "heartbeat" to enable keep-alive newline heartbeats during long-running requests. Response includes Preference-Applied: heartbeat header when honored. (RFC 7240)
     *
     * @var ?string $prefer
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Prefer')]
    public ?string $prefer = null;

    /**
     * @param  string  $xAccountId
     * @param  Components\MarketingCreateEmailTemplateRequestDto  $marketingCreateEmailTemplateRequestDto
     * @param  ?string  $prefer
     * @phpstan-pure
     */
    public function __construct(string $xAccountId, Components\MarketingCreateEmailTemplateRequestDto $marketingCreateEmailTemplateRequestDto, ?string $prefer = null)
    {
        $this->xAccountId = $xAccountId;
        $this->marketingCreateEmailTemplateRequestDto = $marketingCreateEmailTemplateRequestDto;
        $this->prefer = $prefer;
    }
}