<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Utils\SpeakeasyMetadata;
class StackoneListActionsMetaRequest
{
    /**
     * The number of results per page (default value is 25)
     *
     * @var ?string $pageSize
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page_size')]
    public ?string $pageSize = null;

    /**
     * The unified cursor
     *
     * @var ?string $next
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=next')]
    public ?string $next = null;

    /**
     * Actions Metadata filters
     *
     * @var ?StackoneListActionsMetaQueryParamFilter $filter
     */
    #[SpeakeasyMetadata('queryParam:style=deepObject,explode=true,name=filter')]
    public ?StackoneListActionsMetaQueryParamFilter $filter = null;

    /**
     * Additional data to include in the response
     *
     * @var ?array<StackoneListActionsMetaQueryParamInclude> $include
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include')]
    public ?array $include = null;

    /**
     * Text search across provider names, action labels, and action descriptions
     *
     * @var ?string $search
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=search')]
    public ?string $search = null;

    /**
     * Data to exclude from the response
     *
     * @var ?array<Exclude> $exclude
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=exclude')]
    public ?array $exclude = null;

    /**
     * The relation to group the results by
     *
     * @var ?string $groupBy
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=group_by')]
    public ?string $groupBy = null;

    /**
     * @param  ?string  $pageSize
     * @param  ?string  $next
     * @param  ?string  $groupBy
     * @param  ?StackoneListActionsMetaQueryParamFilter  $filter
     * @param  ?array<StackoneListActionsMetaQueryParamInclude>  $include
     * @param  ?string  $search
     * @param  ?array<Exclude>  $exclude
     * @phpstan-pure
     */
    public function __construct(?string $pageSize = null, ?string $next = null, ?StackoneListActionsMetaQueryParamFilter $filter = null, ?array $include = null, ?string $search = null, ?array $exclude = null, ?string $groupBy = 'connector')
    {
        $this->pageSize = $pageSize;
        $this->next = $next;
        $this->filter = $filter;
        $this->include = $include;
        $this->search = $search;
        $this->exclude = $exclude;
        $this->groupBy = $groupBy;
    }
}