<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Models\Components;
use StackOne\client\Utils\SpeakeasyMetadata;
class StackoneRpcActionRequest
{
    /**
     * The account identifier
     *
     * @var string $xAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-account-id')]
    public string $xAccountId;

    /**
     *
     * @var Components\ActionsRpcRequestDto $actionsRpcRequestDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\ActionsRpcRequestDto $actionsRpcRequestDto;

    /**
     * @param  string  $xAccountId
     * @param  Components\ActionsRpcRequestDto  $actionsRpcRequestDto
     * @phpstan-pure
     */
    public function __construct(string $xAccountId, Components\ActionsRpcRequestDto $actionsRpcRequestDto)
    {
        $this->xAccountId = $xAccountId;
        $this->actionsRpcRequestDto = $actionsRpcRequestDto;
    }
}