<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Operations;

use StackOne\client\Models\Components;
use StackOne\client\Utils\SpeakeasyMetadata;
class StackoneMcpPostRequest
{
    /**
     * JSON-RPC 2.0 message
     *
     * @var Components\JsonRpcMessageDto $jsonRpcMessageDto
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\JsonRpcMessageDto $jsonRpcMessageDto;

    /**
     * Account secure id for the target provider account (optional if x-account-id query parameter is provided)
     *
     * @var ?string $xAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-account-id')]
    public ?string $xAccountId = null;

    /**
     * Account secure id (alternative to x-account-id header)
     *
     * @var mixed $xAccountIdQueryParameter
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=x-account-id')]
    public mixed $xAccountIdQueryParameter = null;

    /**
     * Session id; omit for initialize, include for subsequent calls
     *
     * @var ?string $mcpSessionId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=mcp-session-id')]
    public ?string $mcpSessionId = null;

    /**
     * @param  Components\JsonRpcMessageDto  $jsonRpcMessageDto
     * @param  ?string  $xAccountId
     * @param  mixed  $xAccountIdQueryParameter
     * @param  ?string  $mcpSessionId
     * @phpstan-pure
     */
    public function __construct(Components\JsonRpcMessageDto $jsonRpcMessageDto, ?string $xAccountId = null, mixed $xAccountIdQueryParameter = null, ?string $mcpSessionId = null)
    {
        $this->jsonRpcMessageDto = $jsonRpcMessageDto;
        $this->xAccountId = $xAccountId;
        $this->xAccountIdQueryParameter = $xAccountIdQueryParameter;
        $this->mcpSessionId = $mcpSessionId;
    }
}