<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ActionSearchResponseDto
{
    /**
     * $results
     *
     * @var array<ActionSearchResultDto> $results
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('results')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\ActionSearchResultDto>')]
    public array $results;

    /**
     * Total number of results returned
     *
     * @var float $totalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_count')]
    public float $totalCount;

    /**
     * Original search query
     *
     * @var string $query
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('query')]
    public string $query;

    /**
     * Connector filter applied
     *
     * @var ?string $connectorFilter
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connector_filter')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $connectorFilter = null;

    /**
     * Project filter applied
     *
     * @var ?string $projectFilter
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('project_filter')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $projectFilter = null;

    /**
     * @param  array<ActionSearchResultDto>  $results
     * @param  float  $totalCount
     * @param  string  $query
     * @param  ?string  $connectorFilter
     * @param  ?string  $projectFilter
     * @phpstan-pure
     */
    public function __construct(array $results, float $totalCount, string $query, ?string $connectorFilter = null, ?string $projectFilter = null)
    {
        $this->results = $results;
        $this->totalCount = $totalCount;
        $this->query = $query;
        $this->connectorFilter = $connectorFilter;
        $this->projectFilter = $projectFilter;
    }
}