<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ActionBuildResponseDto
{
    /**
     * Build status
     *
     * @var ActionBuildResponseDtoStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\ActionBuildResponseDtoStatus')]
    public ActionBuildResponseDtoStatus $status;

    /**
     * Number of actions indexed
     *
     * @var float $actionsIndexed
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('actions_indexed')]
    public float $actionsIndexed;

    /**
     * Connector filter applied
     *
     * @var ?string $connectorFilter
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connector_filter')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $connectorFilter = null;

    /**
     * Error message if status is error
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $error = null;

    /**
     * @param  ActionBuildResponseDtoStatus  $status
     * @param  float  $actionsIndexed
     * @param  ?string  $connectorFilter
     * @param  ?string  $error
     * @phpstan-pure
     */
    public function __construct(ActionBuildResponseDtoStatus $status, float $actionsIndexed, ?string $connectorFilter = null, ?string $error = null)
    {
        $this->status = $status;
        $this->actionsIndexed = $actionsIndexed;
        $this->connectorFilter = $connectorFilter;
        $this->error = $error;
    }
}