<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ActionSearchResultDto
{
    /**
     * Action identifier (e.g. "slack_send_message")
     *
     * @var string $actionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('action_id')]
    public string $actionId;

    /**
     * Connector key
     *
     * @var string $connectorKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connector_key')]
    public string $connectorKey;

    /**
     * Connector version
     *
     * @var string $connectorVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connector_version')]
    public string $connectorVersion;

    /**
     * Action type (e.g. "custom", "create", "list")
     *
     * @var string $actionType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('action_type')]
    public string $actionType;

    /**
     * Cosine similarity score (0-1)
     *
     * @var float $similarityScore
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('similarity_score')]
    public float $similarityScore;

    /**
     * Human-readable action label
     *
     * @var string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    public string $label;

    /**
     * Action description
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Project ID of the action (global for shared actions)
     *
     * @var string $projectId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('project_id')]
    public string $projectId;

    /**
     * MCP-compatible JSON Schema describing the action input parameters
     *
     * @var InputSchema $inputSchema
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('input_schema')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\InputSchema')]
    public InputSchema $inputSchema;

    /**
     * @param  string  $actionId
     * @param  string  $connectorKey
     * @param  string  $connectorVersion
     * @param  string  $actionType
     * @param  float  $similarityScore
     * @param  string  $label
     * @param  string  $description
     * @param  string  $projectId
     * @param  InputSchema  $inputSchema
     * @phpstan-pure
     */
    public function __construct(string $actionId, string $connectorKey, string $connectorVersion, string $actionType, float $similarityScore, string $label, string $description, string $projectId, InputSchema $inputSchema)
    {
        $this->actionId = $actionId;
        $this->connectorKey = $connectorKey;
        $this->connectorVersion = $connectorVersion;
        $this->actionType = $actionType;
        $this->similarityScore = $similarityScore;
        $this->label = $label;
        $this->description = $description;
        $this->projectId = $projectId;
        $this->inputSchema = $inputSchema;
    }
}