<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ActionBuildDto
{
    /**
     * Specific connector key to rebuild embeddings for
     *
     * @var ?string $connectorKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connector_key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $connectorKey = null;

    /**
     * Force refresh - clear all existing embeddings before rebuilding
     *
     * @var ?bool $forceRefresh
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('force_refresh')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $forceRefresh = null;

    /**
     * @param  ?string  $connectorKey
     * @param  ?bool  $forceRefresh
     * @phpstan-pure
     */
    public function __construct(?string $connectorKey = null, ?bool $forceRefresh = false)
    {
        $this->connectorKey = $connectorKey;
        $this->forceRefresh = $forceRefresh;
    }
}