<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ActionSearchResultDto
{
    /**
     * Unique action identifier
     *
     * @var string $actionName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('action_name')]
    public string $actionName;

    /**
     * Connector key
     *
     * @var string $connectorKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connector_key')]
    public string $connectorKey;

    /**
     * Cosine similarity score (0-1)
     *
     * @var float $similarityScore
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('similarity_score')]
    public float $similarityScore;

    /**
     * Human-readable action label
     *
     * @var string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    public string $label;

    /**
     * Action description
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Project ID of the action (global for shared actions)
     *
     * @var string $projectId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('project_id')]
    public string $projectId;

    /**
     * @param  string  $actionName
     * @param  string  $connectorKey
     * @param  float  $similarityScore
     * @param  string  $label
     * @param  string  $description
     * @param  string  $projectId
     * @phpstan-pure
     */
    public function __construct(string $actionName, string $connectorKey, float $similarityScore, string $label, string $description, string $projectId)
    {
        $this->actionName = $actionName;
        $this->connectorKey = $connectorKey;
        $this->similarityScore = $similarityScore;
        $this->label = $label;
        $this->description = $description;
        $this->projectId = $projectId;
    }
}