<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ActionSearchDto
{
    /**
     * Search query for finding connector actions
     *
     * @var string $query
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('query')]
    public string $query;

    /**
     * Filter by connector key
     *
     * @var ?string $connector
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connector')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $connector = null;

    /**
     * Number of results to return
     *
     * @var ?float $topK
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('top_k')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $topK = null;

    /**
     * @param  string  $query
     * @param  ?string  $connector
     * @param  ?float  $topK
     * @phpstan-pure
     */
    public function __construct(string $query, ?string $connector = null, ?float $topK = 100)
    {
        $this->query = $query;
        $this->connector = $connector;
        $this->topK = $topK;
    }
}