<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ActionsRpcResponse
{
    /**
     * Cursor for fetching the next page of results
     *
     * @var ?string $next
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('next')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $next = null;

    /**
     * The response data from the action RPC call
     *
     * @var array<string, mixed>|array<array<string, mixed>>|null $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|array<array<string, mixed>>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $data = null;

    /**
     * @param  ?string  $next
     * @param  array<string, mixed>|array<array<string, mixed>>|null  $data
     * @phpstan-pure
     */
    public function __construct(?string $next = null, ?array $data = null)
    {
        $this->next = $next;
        $this->data = $data;
    }
}