<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ActionMetaItem
{
    /**
     * The action ID
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * The action label
     *
     * @var ?string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $label = null;

    /**
     * The action description
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * The schema type for the action
     *
     * @var ?string $schemaType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('schema_type')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $schemaType = null;

    /**
     * The tags associated with this action
     *
     * @var ?array<string> $tags
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tags')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $tags = null;

    /**
     * The authentication methods supported by this action
     *
     * @var ?array<AuthenticationMetaItem> $authentication
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authentication')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\AuthenticationMetaItem>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $authentication = null;

    /**
     * The action details for the action
     *
     * @var ?array<string, mixed> $actionDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('action_details')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $actionDetails = null;

    /**
     * The required scopes for the action
     *
     * @var ?array<string> $requiredScopes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('required_scopes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $requiredScopes = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $label
     * @param  ?string  $description
     * @param  ?string  $schemaType
     * @param  ?array<string>  $tags
     * @param  ?array<AuthenticationMetaItem>  $authentication
     * @param  ?array<string, mixed>  $actionDetails
     * @param  ?array<string>  $requiredScopes
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $label = null, ?string $description = null, ?string $schemaType = null, ?array $tags = null, ?array $authentication = null, ?array $actionDetails = null, ?array $requiredScopes = null)
    {
        $this->id = $id;
        $this->label = $label;
        $this->description = $description;
        $this->schemaType = $schemaType;
        $this->tags = $tags;
        $this->authentication = $authentication;
        $this->actionDetails = $actionDetails;
        $this->requiredScopes = $requiredScopes;
    }
}