<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** Build status */
enum ActionBuildResponseDtoStatus: string
{
    case Accepted = 'accepted';
    case Success = 'success';
    case Error = 'error';
}
