<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class AssessmentsOrder
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Provider's unique identifier
     *
     * @var ?string $remoteId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('remote_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $remoteId = null;

    /**
     *
     * @var ?AssessmentsOrderPackage $package
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('package')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AssessmentsOrderPackage|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AssessmentsOrderPackage $package = null;

    /**
     *
     * @var ?AssessmentsOrderApplication $application
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('application')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AssessmentsOrderApplication|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AssessmentsOrderApplication $application = null;

    /**
     *
     * @var ?AssessmentsOrderJob $job
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('job')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AssessmentsOrderJob|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AssessmentsOrderJob $job = null;

    /**
     *
     * @var ?AssessmentsOrderCandidate $candidate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('candidate')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AssessmentsOrderCandidate|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AssessmentsOrderCandidate $candidate = null;

    /**
     *
     * @var ?AssessmentsOrderRequester $requester
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('requester')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AssessmentsOrderRequester|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AssessmentsOrderRequester $requester = null;

    /**
     * Results update url
     *
     * @var ?string $resultsUpdateUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('results_update_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $resultsUpdateUrl = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $remoteId
     * @param  ?AssessmentsOrderPackage  $package
     * @param  ?AssessmentsOrderApplication  $application
     * @param  ?AssessmentsOrderJob  $job
     * @param  ?AssessmentsOrderCandidate  $candidate
     * @param  ?AssessmentsOrderRequester  $requester
     * @param  ?string  $resultsUpdateUrl
     */
    public function __construct(?string $id = null, ?string $remoteId = null, ?AssessmentsOrderPackage $package = null, ?AssessmentsOrderApplication $application = null, ?AssessmentsOrderJob $job = null, ?AssessmentsOrderCandidate $candidate = null, ?AssessmentsOrderRequester $requester = null, ?string $resultsUpdateUrl = null)
    {
        $this->id = $id;
        $this->remoteId = $remoteId;
        $this->package = $package;
        $this->application = $application;
        $this->job = $job;
        $this->candidate = $candidate;
        $this->requester = $requester;
        $this->resultsUpdateUrl = $resultsUpdateUrl;
    }
}