<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class AssessmentsAttachment
{
    /**
     * The URL of the attachment.
     *
     * @var ?string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $url = null;

    /**
     *
     * @var ?AssessmentsAttachmentContentType $contentType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('content_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AssessmentsAttachmentContentType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AssessmentsAttachmentContentType $contentType = null;

    /**
     * @param  ?string  $url
     * @param  ?AssessmentsAttachmentContentType  $contentType
     */
    public function __construct(?string $url = null, ?AssessmentsAttachmentContentType $contentType = null)
    {
        $this->url = $url;
        $this->contentType = $contentType;
    }
}