<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class AssessmentsOrderApplicationStatus
{
    /**
     * The status of the application.
     *
     * @var ?AssessmentsOrderValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\AssessmentsOrderValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AssessmentsOrderValue $value = null;

    /**
     * The source value of the application status.
     *
     * @var string|float|bool|AssessmentsOrderSourceValue4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\AssessmentsOrderSourceValue4|array<mixed>')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|AssessmentsOrderSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?AssessmentsOrderValue  $value
     * @param  string|float|bool|AssessmentsOrderSourceValue4|array<mixed>|null  $sourceValue
     */
    public function __construct(?AssessmentsOrderValue $value = null, string|float|bool|AssessmentsOrderSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}