<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class AuthenticationMetaItem
{
    /**
     * The authentication type
     *
     * @var ?string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     * The authentication label
     *
     * @var ?string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $label = null;

    /**
     * The authentication key
     *
     * @var ?string $key
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     * The required scopes for this authentication method
     *
     * @var ?array<string> $requiredScopes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('required_scopes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $requiredScopes = null;

    /**
     * The support information for this authentication method, including configuration and account linking guides
     *
     * @var ?Support $support
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('support')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\Support|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Support $support = null;

    /**
     * @param  ?string  $type
     * @param  ?string  $label
     * @param  ?string  $key
     * @param  ?array<string>  $requiredScopes
     * @param  ?Support  $support
     * @phpstan-pure
     */
    public function __construct(?string $type = null, ?string $label = null, ?string $key = null, ?array $requiredScopes = null, ?Support $support = null)
    {
        $this->type = $type;
        $this->label = $label;
        $this->key = $key;
        $this->requiredScopes = $requiredScopes;
        $this->support = $support;
    }
}