<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class BackgroundCheckResultsResultResult
{
    /**
     * The result of the test.
     *
     * @var ?BackgroundCheckResultsResultValue $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\BackgroundCheckResultsResultValue|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BackgroundCheckResultsResultValue $value = null;

    /**
     * The source value of the test result.
     *
     * @var string|float|bool|BackgroundCheckResultsResultSourceValue4|array<mixed>|null $sourceValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_value')]
    #[\Speakeasy\Serializer\Annotation\Type('string|float|bool|\StackOne\client\Models\Components\BackgroundCheckResultsResultSourceValue4|array<mixed>')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public string|float|bool|BackgroundCheckResultsResultSourceValue4|array|null $sourceValue = null;

    /**
     * @param  ?BackgroundCheckResultsResultValue  $value
     * @param  string|float|bool|BackgroundCheckResultsResultSourceValue4|array<mixed>|null  $sourceValue
     */
    public function __construct(?BackgroundCheckResultsResultValue $value = null, string|float|bool|BackgroundCheckResultsResultSourceValue4|array|null $sourceValue = null)
    {
        $this->value = $value;
        $this->sourceValue = $sourceValue;
    }
}