<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class BackgroundCheckOrderApplication
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?BackgroundCheckOrderApplicationStatus $applicationStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('application_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\BackgroundCheckOrderApplicationStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BackgroundCheckOrderApplicationStatus $applicationStatus = null;

    /**
     * Value to pass through to the provider
     *
     * @var ?array<string, mixed> $passthrough
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('passthrough')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $passthrough = null;

    /**
     * @param  ?string  $id
     * @param  ?BackgroundCheckOrderApplicationStatus  $applicationStatus
     * @param  ?array<string, mixed>  $passthrough
     */
    public function __construct(?string $id = null, ?BackgroundCheckOrderApplicationStatus $applicationStatus = null, ?array $passthrough = null)
    {
        $this->id = $id;
        $this->applicationStatus = $applicationStatus;
        $this->passthrough = $passthrough;
    }
}