<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class BackgroundCheckOrderPackage
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Package name
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * Package description
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Package tests
     *
     * @var ?array<AssessmentsPackagesTestApiModel> $tests
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tests')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\AssessmentsPackagesTestApiModel>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $tests = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $name
     * @param  ?string  $description
     * @param  ?array<AssessmentsPackagesTestApiModel>  $tests
     */
    public function __construct(?string $id = null, ?string $name = null, ?string $description = null, ?array $tests = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->description = $description;
        $this->tests = $tests;
    }
}