<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class BackgroundCheckOrderJob
{
    /**
     * Unique identifier
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Title of the job
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * Value to pass through to the provider
     *
     * @var ?array<string, mixed> $passthrough
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('passthrough')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $passthrough = null;

    /**
     * Hiring team for the job.
     *
     * @var ?array<AssessmentsRequestsJobHiringTeamApiModel> $hiringTeam
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hiring_team')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\AssessmentsRequestsJobHiringTeamApiModel>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $hiringTeam = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $title
     * @param  ?array<string, mixed>  $passthrough
     * @param  ?array<AssessmentsRequestsJobHiringTeamApiModel>  $hiringTeam
     */
    public function __construct(?string $id = null, ?string $title = null, ?array $passthrough = null, ?array $hiringTeam = null)
    {
        $this->id = $id;
        $this->title = $title;
        $this->passthrough = $passthrough;
        $this->hiringTeam = $hiringTeam;
    }
}