<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** Config - Configuration guide */
class Config
{
    /**
     * The guide sections
     *
     * @var array<GuideSectionMeta> $sections
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sections')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\GuideSectionMeta>')]
    public array $sections;

    /**
     * Warning text for the guide
     *
     * @var ?string $warning
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('warning')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $warning = null;

    /**
     * @param  array<GuideSectionMeta>  $sections
     * @param  ?string  $warning
     * @phpstan-pure
     */
    public function __construct(array $sections, ?string $warning = null)
    {
        $this->sections = $sections;
        $this->warning = $warning;
    }
}