<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** DefenderConfig - Per-request defender configuration. Takes precedence over defender_enabled and project settings. */
class DefenderConfig
{
    /**
     * Whether to run defender at all
     *
     * @var ?bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $enabled = null;

    /**
     * Whether to block tool execution when a HIGH risk score is detected
     *
     * @var ?bool $blockHighRisk
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('block_high_risk')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $blockHighRisk = null;

    /**
     * Whether to run tier 1 pattern-based detection
     *
     * @var ?bool $useTier1Classification
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('use_tier1_classification')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $useTier1Classification = null;

    /**
     * Whether to run tier 2 ML-based detection
     *
     * @var ?bool $useTier2Classification
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('use_tier2_classification')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $useTier2Classification = null;

    /**
     * @param  ?bool  $enabled
     * @param  ?bool  $blockHighRisk
     * @param  ?bool  $useTier1Classification
     * @param  ?bool  $useTier2Classification
     * @phpstan-pure
     */
    public function __construct(?bool $enabled = null, ?bool $blockHighRisk = null, ?bool $useTier1Classification = null, ?bool $useTier2Classification = null)
    {
        $this->enabled = $enabled;
        $this->blockHighRisk = $blockHighRisk;
        $this->useTier1Classification = $useTier1Classification;
        $this->useTier2Classification = $useTier2Classification;
    }
}