<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class EntitySkillsCreateRequestDto
{
    /**
     * The ID associated with this skill
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * The name associated with this skill
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * The proficiency level of the skill
     *
     * @var ?MaximumProficiency $maximumProficiency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maximum_proficiency')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\MaximumProficiency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MaximumProficiency $maximumProficiency = null;

    /**
     * The proficiency level of the skill
     *
     * @var ?MinimumProficiency $minimumProficiency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('minimum_proficiency')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\MinimumProficiency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MinimumProficiency $minimumProficiency = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $name
     * @param  ?MaximumProficiency  $maximumProficiency
     * @param  ?MinimumProficiency  $minimumProficiency
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $name = null, ?MaximumProficiency $maximumProficiency = null, ?MinimumProficiency $minimumProficiency = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->maximumProficiency = $maximumProficiency;
        $this->minimumProficiency = $minimumProficiency;
    }
}