<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** Guides - Authentication guides for this authentication type */
class Guides
{
    /**
     * Configuration guide
     *
     * @var ?Config $config
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('config')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\Config|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Config $config = null;

    /**
     * Account linking guide
     *
     * @var ?Setup $setup
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('setup')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\Setup|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Setup $setup = null;

    /**
     * @param  ?Config  $config
     * @param  ?Setup  $setup
     * @phpstan-pure
     */
    public function __construct(?Config $config = null, ?Setup $setup = null)
    {
        $this->config = $config;
        $this->setup = $setup;
    }
}