<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class GuideStepMeta
{
    /**
     * The title of the step
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     * The content of the step, includes markdown formatting
     *
     * @var string $content
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('content')]
    public string $content;

    /**
     * List items for the step
     *
     * @var ?array<string> $list
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('list')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $list = null;

    /**
     * @param  string  $title
     * @param  string  $content
     * @param  ?array<string>  $list
     * @phpstan-pure
     */
    public function __construct(string $title, string $content, ?array $list = null)
    {
        $this->title = $title;
        $this->content = $content;
        $this->list = $list;
    }
}