<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class GuideStepMeta
{
    /**
     * The title of the step
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     * The content of the step, includes markdown formatting
     *
     * @var string $content
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('content')]
    public string $content;

    /**
     * List items for the step
     *
     * @var ?array<string> $list
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('list')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $list = null;

    /**
     * When true, the step should display scopes
     *
     * @var ?bool $displayScopes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('displayScopes')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $displayScopes = null;

    /**
     * The scopes for which this step is applicable
     *
     * @var ?array<string> $applicableScopes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('applicableScopes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $applicableScopes = null;

    /**
     * An image for the step
     *
     * @var ?Image $image
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\Image|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Image $image = null;

    /**
     * @param  string  $title
     * @param  string  $content
     * @param  ?array<string>  $list
     * @param  ?bool  $displayScopes
     * @param  ?array<string>  $applicableScopes
     * @param  ?Image  $image
     * @phpstan-pure
     */
    public function __construct(string $title, string $content, ?array $list = null, ?bool $displayScopes = null, ?array $applicableScopes = null, ?Image $image = null)
    {
        $this->title = $title;
        $this->content = $content;
        $this->list = $list;
        $this->displayScopes = $displayScopes;
        $this->applicableScopes = $applicableScopes;
        $this->image = $image;
    }
}