<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class GuideSectionMeta
{
    /**
     * The title of the section
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     * The content of the section, includes markdown formatting
     *
     * @var string $content
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('content')]
    public string $content;

    /**
     * List items for the section
     *
     * @var ?array<string> $list
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('list')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $list = null;

    /**
     * Nested steps within the section
     *
     * @var ?array<GuideStepMeta> $steps
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('steps')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\GuideStepMeta>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $steps = null;

    /**
     * The scopes for which this section is applicable
     *
     * @var ?array<string> $applicableScopes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('applicableScopes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $applicableScopes = null;

    /**
     * An image for the section
     *
     * @var ?GuideSectionMetaImage $image
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\GuideSectionMetaImage|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?GuideSectionMetaImage $image = null;

    /**
     * @param  string  $title
     * @param  string  $content
     * @param  ?array<string>  $list
     * @param  ?array<GuideStepMeta>  $steps
     * @param  ?array<string>  $applicableScopes
     * @param  ?GuideSectionMetaImage  $image
     * @phpstan-pure
     */
    public function __construct(string $title, string $content, ?array $list = null, ?array $steps = null, ?array $applicableScopes = null, ?GuideSectionMetaImage $image = null)
    {
        $this->title = $title;
        $this->content = $content;
        $this->list = $list;
        $this->steps = $steps;
        $this->applicableScopes = $applicableScopes;
        $this->image = $image;
    }
}