<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** GuideSectionMetaImage - An image for the section */
class GuideSectionMetaImage
{
    /**
     * The image source URL or relative path
     *
     * @var string $src
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('src')]
    public string $src;

    /**
     * The image alt text
     *
     * @var string $alt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('alt')]
    public string $alt;

    /**
     * @param  string  $src
     * @param  string  $alt
     * @phpstan-pure
     */
    public function __construct(string $src, string $alt)
    {
        $this->src = $src;
        $this->alt = $alt;
    }
}