<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** InputSchema - MCP-compatible JSON Schema describing the action input parameters */
class InputSchema
{

    public function __construct()
    {
    }
}