<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** LmsCreateCompletionRequestDtoScore - The score associated with this completion */
class LmsCreateCompletionRequestDtoScore
{
    /**
     * The score percentage
     *
     * @var ?float $percentage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('percentage')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $percentage = null;

    /**
     * The raw string score value
     *
     * @var ?string $rawValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('raw_value')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $rawValue = null;

    /**
     * @param  ?float  $percentage
     * @param  ?string  $rawValue
     * @phpstan-pure
     */
    public function __construct(?float $percentage = null, ?string $rawValue = null)
    {
        $this->percentage = $percentage;
        $this->rawValue = $rawValue;
    }
}