<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class LocalisationModel
{
    /**
     * The title of the content
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * The description of the content
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * The language associated with this localisation details
     *
     * @var ?LocalisationModelLanguage $language
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('language')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\LocalisationModelLanguage|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalisationModelLanguage $language = null;

    /**
     * @param  ?string  $title
     * @param  ?string  $description
     * @param  ?LocalisationModelLanguage  $language
     * @phpstan-pure
     */
    public function __construct(?string $title = null, ?string $description = null, ?LocalisationModelLanguage $language = null)
    {
        $this->title = $title;
        $this->description = $description;
        $this->language = $language;
    }
}