<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ProxyResponseApiModel
{
    /**
     * The HTTP status code returned by the provider
     *
     * @var float $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    public float $status;

    /**
     * The headers returned by the provider
     *
     * @var ?array<string, mixed> $headers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('headers')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $headers = null;

    /**
     * The response data from the provider. Can be an object, array, or primitive value.
     *
     * @var array<string, mixed>|array<array<string, mixed>>|string|float|bool|null $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|array<array<string, mixed>>|string|float|bool|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public array|string|float|bool|null $data = null;

    /**
     * Provider-specific errors if any occurred
     *
     * @var ?array<ProviderErrorApiModel> $providerErrors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider_errors')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\StackOne\client\Models\Components\ProviderErrorApiModel>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $providerErrors = null;

    /**
     * @param  float  $status
     * @param  ?array<string, mixed>  $headers
     * @param  array<string, mixed>|array<array<string, mixed>>|string|float|bool|null  $data
     * @param  ?array<ProviderErrorApiModel>  $providerErrors
     * @phpstan-pure
     */
    public function __construct(float $status, array|string|float|bool|null $data = null, ?array $providerErrors = null, ?array $headers = null)
    {
        $this->status = $status;
        $this->headers = $headers;
        $this->data = $data;
        $this->providerErrors = $providerErrors;
    }
}