<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** Query - Query parameters for the action */
class Query
{
    /**
     * $additionalProperties
     *
     * @var ?array<string, mixed> $additionalProperties
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('additionalProperties')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $additionalProperties = null;

    /**
     * Enable debug mode for the action execution
     *
     * @var ?bool $debug
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('debug')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $debug = null;

    /**
     * @param  ?array<string, mixed>  $additionalProperties
     * @param  ?bool  $debug
     * @phpstan-pure
     */
    public function __construct(?array $additionalProperties = null, ?bool $debug = null)
    {
        $this->additionalProperties = $additionalProperties;
        $this->debug = $debug;
    }
}