<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class ScopeDefinitionMetaItem
{
    /**
     * The scope name
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * The scope description
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * The scopes auto-included within this scope
     *
     * @var ?array<string> $includes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('includes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $includes = null;

    /**
     * @param  string  $name
     * @param  string  $description
     * @param  ?array<string>  $includes
     * @phpstan-pure
     */
    public function __construct(string $name, string $description, ?array $includes = null)
    {
        $this->name = $name;
        $this->description = $description;
        $this->includes = $includes;
    }
}