<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** Scopes - The scopes restrictions, if any, for the token generated from this connect session */
class Scopes
{

    public function __construct()
    {
    }
}