<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


/** Support - The support information for this authentication method, including configuration and account linking guides */
class Support
{
    /**
     * Link to support documentation
     *
     * @var ?string $link
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('link')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $link = null;

    /**
     * Support description
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Authentication guides for this authentication type
     *
     * @var ?Guides $guides
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('guides')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\Guides|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Guides $guides = null;

    /**
     * @param  ?string  $link
     * @param  ?string  $description
     * @param  ?Guides  $guides
     * @phpstan-pure
     */
    public function __construct(?string $link = null, ?string $description = null, ?Guides $guides = null)
    {
        $this->link = $link;
        $this->description = $description;
        $this->guides = $guides;
    }
}