<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace StackOne\client\Models\Components;


class UpdateUserApiModel
{
    /**
     * Primary email address of the user. This is generally a work email address.
     *
     * @var ?string $primaryEmailAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('primary_email_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $primaryEmailAddress = null;

    /**
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $firstName = null;

    /**
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lastName = null;

    /**
     * User's name which (can be a full name or display name)
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?string $username
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('username')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $username = null;

    /**
     * Indicates if the user is a bot or service user
     *
     * @var bool|UpdateUserApiModelIsBotUser2|null $isBotUser
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_bot_user')]
    #[\Speakeasy\Serializer\Annotation\Type('bool|\StackOne\client\Models\Components\UpdateUserApiModelIsBotUser2|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public bool|UpdateUserApiModelIsBotUser2|null $isBotUser = null;

    /**
     *
     * @var ?UpdateUserApiModelStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\StackOne\client\Models\Components\UpdateUserApiModelStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateUserApiModelStatus $status = null;

    /**
     * Value to pass through to the provider
     *
     * @var ?array<string, mixed> $passthrough
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('passthrough')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $passthrough = null;

    /**
     * @param  ?string  $primaryEmailAddress
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?string  $name
     * @param  ?string  $username
     * @param  bool|UpdateUserApiModelIsBotUser2|null  $isBotUser
     * @param  ?UpdateUserApiModelStatus  $status
     * @param  ?array<string, mixed>  $passthrough
     * @phpstan-pure
     */
    public function __construct(?string $primaryEmailAddress = null, ?string $firstName = null, ?string $lastName = null, ?string $name = null, ?string $username = null, bool|UpdateUserApiModelIsBotUser2|null $isBotUser = null, ?UpdateUserApiModelStatus $status = null, ?array $passthrough = null)
    {
        $this->primaryEmailAddress = $primaryEmailAddress;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->name = $name;
        $this->username = $username;
        $this->isBotUser = $isBotUser;
        $this->status = $status;
        $this->passthrough = $passthrough;
    }
}